### ISSUE TITLE
When I add forward_to as action, outlook rules include both forward and redirect

### ISSUE THREAD

**Issue by gokhancann** [magodo/terraform-provider-outlook#17]
I add forward_to argument as action. After that I plan and apply it. Then, when I check outlook rules in my mailbox, I can see both forward and redirect for same e-mail addresses.

**Comment by gokhancann** [comment]
I think problem is in #537. There is "forward_to" inside "RedirectTo" element. But I'm not sure, just an opinion.

path: magodo/terraform-provider-outlook/blob/master/outlook/services/message_rule_resource.go

**Comment by magodo** [comment]
@gokhancann Thank you for pointing the bug! I'll make a fix soon!
